# Generated by Django 4.1.7 on 2023-03-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_lead',
        ),
    ]
